### ISSUE TITLE
result_ttl type problem with repeated jobs on PY3

### ISSUE THREAD

**Issue by ggold6** [ui/rq-scheduler#79]
all, on PY3 i'm getting the following error when adding result_ttl=interval*1.1 argument on scheduler:

<pre><code>
Traceback (most recent call last):
  File "/api/apivenv3/bin/rqscheduler", line 11, in <module>
    sys.exit(main())
  File "/api/apivenv3/lib/python3.4/site-packages/rq_scheduler/scripts/rqscheduler.py", line 52, in main
    scheduler.run()
  File "/api/apivenv3/lib/python3.4/site-packages/rq_scheduler/scheduler.py", line 312, in run
    self.enqueue_jobs()
  File "api/apivenv3/lib/python3.4/site-packages/rq_scheduler/scheduler.py", line 294, in enqueue_jobs
    jobs = self.get_jobs_to_queue()
  File "/api/apivenv3/lib/python3.4/site-packages/rq_scheduler/scheduler.py", line 249, in get_jobs_to_queue
    return self.get_jobs(to_unix(datetime.utcnow()), with_times=with_times)
  File "/api/apivenv3/lib/python3.4/site-packages/rq_scheduler/scheduler.py", line 232, in get_jobs
    job = Job.fetch(job_id, connection=self.connection)
  File "/api/apivenv3/lib/python3.4/site-packages/rq/job.py", line 294, in fetch
    job.refresh()
  File "/api/apivenv3/lib/python3.4/site-packages/rq/job.py", line 418, in refresh
    self.result_ttl = int(obj.get('result_ttl')) if obj.get('result_ttl') else None  # noqa
ValueError: invalid literal for int() with base 10: b'33.0'
</code></pre>

adding result_ttl parameter is done so result_ttl is not infinite and jobs that are done do not linger on redis (avoiding <code>Result will never expire, clean up result key manually.</code> message from the worker, as per the documentation note.)

Seems that the problem is not really in rq-sechduler, but RQ? 
Note that adding result_ttl = int(interval*1.1), solves the issue. I was wondering if this is really an issue here, whether to report this on RQ's github issues, or just let it go?

**Comment by selwin** [comment]
Yes, the error is caused by RQ itself. What's the value of "interval" in this case? Is interval an integer?

**Comment by ggold6** [comment]
@selwin (sorry for the late reply) checked it with both int and float types- only when interval is a float this issue happens, integer works fine.

**Comment by selwin** [comment]
No worries. Actually, Redis' `expire` command only works with integers anyway so I think it's ok that we don't accept a float argument.
